name: Third Action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "hello"
      - name: Second Step
        run: |
          echo "first line"
          echo "second line"
